name: Python
on:
  workflow_call:
    secrets:
      PYPI_PASSWORD:
        required: false
      TEST_PYPI_PASSWORD:
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish Snapshot to TestPyPi
        uses: dciborow/pyaction@0.0.30
        continue-on-error: true
        if: ${{ github.event_name == 'pull_request' }}
        with:
          pypi_publish: true
          pypi_password: ${{ secrets.TEST_PYPI_PASSWORD  }}
          pypi_repo: testpypi
          version_suffix: -post${{ github.run_number }}-dev${{ github.run_attempt }}

      - name: Publish RC to PyPi
        uses: dciborow/pyaction@0.0.30
        if: ${{ github.event_name == 'push' }}
        with:
          pypi_publish: true
          pypi_password: ${{ secrets.PYPI_PASSWORD }}
          version_suffix: -rc${{ github.run_number }}-post${{ github.run_attempt }}

      - name: Publish Release to PyPi
        uses: dciborow/pyaction@0.0.30
        if: ${{ github.event_name == 'release' }}
        with:
          pypi_publish: true
          pypi_password: ${{ secrets.PYPI_PASSWORD }}
