name: Python
on:
  workflow_call:    
    inputs:
      workdir:
        type: string
        default: src
      testdir:
        type: string
        default: tests
      python-version: 
        type: string
        default: 3.11.2

jobs:
  validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tools: ['black', 'bandit', 'pylint', 'flake8']
        include:
          - tools: pytest
            args: -m not integration and not gpu
          - tools: pytest
            args: -m integration
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4.6.0
        with:
          # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: ${{ inputs.python-version }}
      - name: ${{ matrix.tools }}
        uses: microsoft/action-python@0.3.15
        with:
          ${{ matrix.tools }}: true
          args: ${{ matrix.args }}
          workdir: ${{ inputs.workdir }}
          testdir: ${{ inputs.testdir }}
