name: Python
on:
  workflow_call:    
    inputs:
      workdir:
        type: string
        default: src
      testdir:
        type: string
        default: tests
      python-version: 
        type: string
        default: 3.11.3

      docker-image:
        type: string
        default: ubuntu
      
    secrets:
      AZURE_CREDENTIALS:
        required: false

      CODECOV_TOKEN:
        required: false


jobs:
  validation:
    runs-on: ubuntu-latest
    container:
        image: ${{ inputs.docker-image }}
    
    strategy:
      matrix:
        tools: ['black', 'bandit', 'pylint', 'flake8']
        include:
          - tools: pytest
            args: -m not integration and not gpu
          - tools: pytest
            args: -m integration
      
    steps:
      - uses: actions/checkout@v4
      - uses: Azure/login@v1.5.1
        continue-on-error: true
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: ${{ matrix.tools }}
        uses: YaoYinYing/action-python@v7.3.1-post-7
        with:
          ${{ matrix.tools }}: true
          args: ${{ matrix.args }}
          workdir: ${{ inputs.workdir }}
          testdir: ${{ inputs.testdir }}
          python_version: ${{ inputs.python-version }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
